export default {
  '06cc208e': [() => import(/* webpackChunkName: '06cc208e' */ "@site/versioned_docs/version-0.2/01-index.md"), "@site/versioned_docs/version-0.2/01-index.md", require.resolveWeak("@site/versioned_docs/version-0.2/01-index.md")],
  '147416ca': [() => import(/* webpackChunkName: '147416ca' */ "@site/versioned_docs/version-0.1/index.md"), "@site/versioned_docs/version-0.1/index.md", require.resolveWeak("@site/versioned_docs/version-0.1/index.md")],
  '17896441': [() => import(/* webpackChunkName: '17896441' */ "@theme/DocItem"), "@theme/DocItem", require.resolveWeak("@theme/DocItem")],
  '1be78505': [() => import(/* webpackChunkName: '1be78505' */ "@theme/DocPage"), "@theme/DocPage", require.resolveWeak("@theme/DocPage")],
  '25183730': [() => import(/* webpackChunkName: '25183730' */ "~docs/default/version-0-2-metadata-prop-240.json"), "~docs/default/version-0-2-metadata-prop-240.json", require.resolveWeak("~docs/default/version-0-2-metadata-prop-240.json")],
  '40687f02': [() => import(/* webpackChunkName: '40687f02' */ "@site/versioned_docs/version-0.2/02-Features/02-Security/auto-invalidate-secrets.md"), "@site/versioned_docs/version-0.2/02-Features/02-Security/auto-invalidate-secrets.md", require.resolveWeak("@site/versioned_docs/version-0.2/02-Features/02-Security/auto-invalidate-secrets.md")],
  '4c85918d': [() => import(/* webpackChunkName: '4c85918d' */ "@site/versioned_docs/version-0.2/02-Features/03-Databricks/job-metrics.md"), "@site/versioned_docs/version-0.2/02-Features/03-Databricks/job-metrics.md", require.resolveWeak("@site/versioned_docs/version-0.2/02-Features/03-Databricks/job-metrics.md")],
  '4d4bbadc': [() => import(/* webpackChunkName: '4d4bbadc' */ "@site/versioned_docs/version-0.2/02-Features/03-Databricks/gain-insights.md"), "@site/versioned_docs/version-0.2/02-Features/03-Databricks/gain-insights.md", require.resolveWeak("@site/versioned_docs/version-0.2/02-Features/03-Databricks/gain-insights.md")],
  '8e100752': [() => import(/* webpackChunkName: '8e100752' */ "@site/versioned_docs/version-0.1/features/cloudevent/receive-cloudevents-job.md"), "@site/versioned_docs/version-0.1/features/cloudevent/receive-cloudevents-job.md", require.resolveWeak("@site/versioned_docs/version-0.1/features/cloudevent/receive-cloudevents-job.md")],
  'c2a24877': [() => import(/* webpackChunkName: 'c2a24877' */ "~docs/default/version-0-1-metadata-prop-f65.json"), "~docs/default/version-0-1-metadata-prop-f65.json", require.resolveWeak("~docs/default/version-0-1-metadata-prop-f65.json")],
  'd954bd67': [() => import(/* webpackChunkName: 'd954bd67' */ "@site/versioned_docs/version-0.1/features/security/auto-invalidate-secrets.md"), "@site/versioned_docs/version-0.1/features/security/auto-invalidate-secrets.md", require.resolveWeak("@site/versioned_docs/version-0.1/features/security/auto-invalidate-secrets.md")],
  'e56b4d05': [() => import(/* webpackChunkName: 'e56b4d05' */ "@site/versioned_docs/version-0.2/02-Features/01-General/receive-cloudevents-job.md"), "@site/versioned_docs/version-0.2/02-Features/01-General/receive-cloudevents-job.md", require.resolveWeak("@site/versioned_docs/version-0.2/02-Features/01-General/receive-cloudevents-job.md")],};
